In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

In [2]:
train_df=pd.read_csv('Train.csv')

In [7]:
train_df['Item_Weight'] = train_df['Item_Weight'].fillna(train_df['Item_Weight'].mean())

In [8]:
train_df['Outlet_Size'] = train_df['Outlet_Size'].fillna('Medium')

In [9]:
train_df['Item_Visibility'] = train_df['Item_Visibility'].replace(0, train_df['Item_Visibility'].mean())

In [10]:

label_encoders = {}
for col in ['Item_Fat_Content', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']:
    le = LabelEncoder()
    train_df[col] = le.fit_transform(train_df[col])
    label_encoders[col] = le

In [12]:
train_df['Item_Fat_Content'] = train_df['Item_Fat_Content'].replace({'low fat': 'Low Fat','LF': 'Low Fat','reg': 'Regular'})

In [13]:
train_df.head(20)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300000,1,0.016047,Dairy,249.8092,OUT049,1999,1,0,1,3735.1380
1,DRC01,5.920000,2,0.019278,Soft Drinks,48.2692,OUT018,2009,1,2,2,443.4228
2,FDN15,17.500000,1,0.016760,Meat,141.6180,OUT049,1999,1,0,1,2097.2700
3,FDX07,19.200000,2,0.066132,Fruits and Vegetables,182.0950,OUT010,1998,1,2,0,732.3800
4,NCD19,8.930000,1,0.066132,Household,53.8614,OUT013,1987,0,2,1,994.7052
5,FDP36,10.395000,2,0.066132,Baking Goods,51.4008,OUT018,2009,1,2,2,556.6088
6,FDO10,13.650000,2,0.012741,Snack Foods,57.6588,OUT013,1987,0,2,1,343.5528
7,FDP10,12.857645,1,0.127470,Snack Foods,107.7622,OUT027,1985,1,2,3,4022.7636
8,FDH17,16.200000,2,0.016687,Frozen Foods,96.9726,OUT045,2002,1,1,1,1076.5986
9,FDU28,19.200000,2,0.094450,Frozen Foods,187.8214,OUT017,2007,1,1,1,4710.5350
10,FDY07,11.800000,1,0.066132,Fruits and Vegetables,45.5402,OUT049,1999,1,0,1,1516.0266
11,FDA03,18.500000,2,0.045464,Dairy,144.1102,OUT046,1997,2,0,1,2187.1530
12,FDX32,15.100000,2,0.100014,Fruits and Vegetables,145.4786,OUT049,1999,1,0,1,1589.2646
13,FDS46,17.600000,2,0.047257,Snack Foods,119.6782,OUT046,1997,2,0,1,2145.2076
14,FDF32,16.350000,1,0.068024,Fruits and Vegetables,196.4426,OUT013,1987,0,2,1,1977.4260
15,FDP49,9.000000,2,0.069089,Breakfast,56.3614,OUT046,1997,2,0,1,1547.3192
16,NCB42,11.800000,1,0.008596,Health and Hygiene,115.3492,OUT018,2009,1,2,2,1621.8888
17,FDP49,9.000000,2,0.069196,Breakfast,54.3614,OUT049,1999,1,0,1,718.3982
18,DRI11,12.857645,1,0.034238,Hard Drinks,113.2834,OUT027,1985,1,2,3,2303.6680
19,FDU02,13.350000,1,0.102492,Dairy,230.5352,OUT035,2004,2,1,1,2748.4224